spring:
  application:
    name: luckmoney
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luckymoney?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: dyx123456
  jpa:
    show-sql: true
    hibernate:
#      含义：每次应用启动时都会删除现有的数据库表结构，并重新创建全新的表结构（测试使用）
      ddl-auto: create

server:
  port: 8081
  servlet:
    context-path: /luckmoney

limit:
  minMoney: 0.01
  maxMoney: 9999
  description: 最少要发${limit.minMoney}元, 最多${limit.maxMoney}元

girl:
  cupSize: B
  age: 18